spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mbc
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver	
  jpa:
    hibernate:
      ddl-auto:update
    show-sql: true		
mybatis:
  config-locatio:classpath: classpath:mappers/*.xml
