spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mbc
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
# spring.jackson.default-property-inclusion: NON_NULL
mybatis:
   config-location: classpath:mybatis-config.xml